AUTOENCODER

In [1]:
import os
import numpy as np
import cv2

CONVOLUTION(3D):

In [2]:
def convolution(data, filter, stride):
    result=np.zeros((int((data.shape[0]-filter.shape[0])/stride[0]) +1,int((data.shape[1]-filter.shape[1])/stride[1]) +1,int((data.shape[2]-filter.shape[2])/stride[2]) +1))
    for i in range(0, result.shape[0], 1):
        for j in range(0, result.shape[1], 1):
            for k in range(0, result.shape[2], 1):
                current_region=data[i*stride[0]:i*stride[0]+filter.shape[0],j*stride[1]:j*stride[1]+filter.shape[1],k*stride[2]:k*stride[2]+filter.shape[2]]
                result[i][j][k]=np.sum(current_region*filter)
    return result

In [3]:
max=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])
filt=np.array([[[1,1,1],[1,1,1],[1,1,1]],[[2,2,2],[2,2,2],[2,2,2]],[[3,3,3],[3,3,3],[3,3,3]]])
ft=np.array([[[1,1],[1,1]],[[2,2],[2,2]],[[3,3],[3,3]]])
strike=np.array([1,1,1],dtype='int32')
convs=convolution(max,filt,strike)
convs

array([[[324., 378.],
        [540., 594.]]])

DECONVOLUTION(3D):

In [4]:
def deconvolution(data,filter,stride):
    result=np.zeros((int(data.shape[0]*stride[0]+filter.shape[0]-stride[0]),int(data.shape[1]*stride[1]+filter.shape[1]-stride[1]),int(data.shape[2]*stride[2]+filter.shape[2]-stride[2])))
    for i in range(0, data.shape[0], 1):
        for j in range(0, data.shape[1], 1):
            for k in range(0, data.shape[2], 1):
                current_region=data[i,j,k]*filter
                result[int(i*stride[0]):int(i*stride[0]+filter.shape[0]), int(j*stride[1]):int(j*stride[1]+filter.shape[1]), int(k*stride[2]):int(k*stride[2]+filter.shape[2])]=result[int(i*stride[0]):int(i*stride[0]+filter.shape[0]), int(j*stride[1]):int(j*stride[1]+filter.shape[1]), int(k*stride[2]):int(k*stride[2]+filter.shape[2])]+current_region
    return result

In [5]:
crap=deconvolution(filt,max,strike)
crap

array([[[  1.,   3.,   6.,   9.,   7.,   4.],
        [  6.,  14.,  24.,  30.,  22.,  12.],
        [ 15.,  33.,  54.,  63.,  45.,  24.],
        [ 27.,  57.,  90.,  99.,  69.,  36.],
        [ 22.,  46.,  72.,  78.,  54.,  28.],
        [ 13.,  27.,  42.,  45.,  31.,  16.]],

       [[  3.,   9.,  18.,  27.,  21.,  12.],
        [ 18.,  42.,  72.,  90.,  66.,  36.],
        [ 45.,  99., 162., 189., 135.,  72.],
        [ 81., 171., 270., 297., 207., 108.],
        [ 66., 138., 216., 234., 162.,  84.],
        [ 39.,  81., 126., 135.,  93.,  48.]],

       [[  6.,  18.,  36.,  54.,  42.,  24.],
        [ 36.,  84., 144., 180., 132.,  72.],
        [ 90., 198., 324., 378., 270., 144.],
        [162., 342., 540., 594., 414., 216.],
        [132., 276., 432., 468., 324., 168.],
        [ 78., 162., 252., 270., 186.,  96.]],

       [[  5.,  15.,  30.,  45.,  35.,  20.],
        [ 30.,  70., 120., 150., 110.,  60.],
        [ 75., 165., 270., 315., 225., 120.],
        [135., 285., 450., 4

MODEL:

In [6]:
#params
conv_filter1=np.random.randn(3,4,4)  #363
#bias1=np.random.rand(1,963,963)  #963*963
stride1=2                    
conv_filter2=np.random.randn(1,4,4)    #25
#bias2=np.random.rand(1,479,479)  #479*479
stride2=1
conv_filter3=np.random.randn(1,2,2)    #9
#bias3=np.random.rand(1,238,238)  #238*238
stride3=1

#reverse

deconv_filter3=np.random.randn(1,2,2)
deconv_filter2=np.random.randn(1,4,4)
deconv_filter1=np.random.randn(3,4,4)

print(conv_filter1)
print(conv_filter2)
print(conv_filter3)
print(deconv_filter1)
print(deconv_filter2)
print(deconv_filter3)

#Using same strides
 
# flow 1-2-3-3-2-1

[[[-0.21669785 -0.24932361  1.11199977 -2.42810199]
  [-0.64813982 -1.34467776  1.78744252 -0.25641487]
  [ 0.38835243 -1.45042759  1.11122211  0.86952336]
  [-0.10802088 -0.40923792  0.65365291 -0.35480225]]

 [[-1.2103408  -0.20977617 -0.54606465  0.44884653]
  [ 1.00487992 -0.01463885 -0.80625557 -0.06558856]
  [ 0.10324571 -0.93925468 -0.35734304  0.47178659]
  [ 1.44303494 -0.47629618  0.73408394  1.00093983]]

 [[-0.11074461 -0.04966091 -0.86245425 -0.49304842]
  [-0.07019113 -1.21773958  0.58846103  0.14654948]
  [ 0.95688456 -0.71504808  1.46779307 -1.14925001]
  [-1.17308348  0.18477626  3.15887558  0.74312835]]]
[[[ 0.86976014  0.06409938 -0.30066274  2.88192536]
  [-0.69132766  1.35270946 -0.16968269 -1.44648214]
  [ 0.26708234  0.02531118  0.40022218 -0.30357643]
  [-0.95167933 -1.18885121  0.42346402  0.07757486]]]
[[[ 0.67479531  0.05053948]
  [-1.78019515 -0.10752841]]]
[[[-1.14121142 -0.60036026  0.74397385 -0.32774232]
  [ 0.16383616 -0.05018473  0.28170469  0.28755723

In [7]:
print(conv_filter3.shape)

(1, 2, 2)


FORWARD PASS:

In [8]:
def forward_pass(IP):
    a1=convolution(IP, conv_filter1, [1,2,2])
    a2=convolution(a1, conv_filter2, [1,1,1])
    a3=convolution(a2, conv_filter3, [1,1,1])    #bottleneck
    a4=deconvolution(a3, deconv_filter3, [1,1,1])
    a5=deconvolution(a4, deconv_filter2, [1,1,1])
    a6=deconvolution(a5, deconv_filter1, [1,2,2])
    return a6, a5, a4, a3, a2, a1

ERROR METRICS:

In [9]:
def square_error(IP,OP):
    error=(IP-OP)**2
    #error=error*error
    #err=np.sum(error)/(IP.shape[0]*IP.shape[1]*IP.shape[2])
    return error

BACKWARD PASS:

In [10]:
def backward_pass(IP, layers):
    a6, a5, a4, a3, a2, a1 = layers
    d_a6 = a6-IP  #3D

    d_deconv_filter1=convolution(d_a6, a5, [1,5,5])   #change
    #print(d_deconv_filter1.shape)
    d_a5=convolution(d_a6, np.transpose(deconv_filter1, (0,2,1)), [1,2,2])

    d_deconv_filter2=convolution(d_a5, a4, [1,1,1])
    #print(d_deconv_filter2.shape)
    d_a4=convolution(d_a5, np.transpose(deconv_filter2, (0,2,1)), [1,1,1])

    d_deconv_filter3=convolution(d_a4, a3, [1,1,1])
    #print(d_deconv_filter3.shape)
    d_a3=convolution(d_a4, np.transpose(deconv_filter3, (0,2,1)),[1,1,1])

    d_conv_filter3=convolution(a2,d_a3,[1,1,1])
    #print(d_conv_filter3.shape)
    d_a2=deconvolution(d_a3, np.transpose(conv_filter3, (0,2,1)), [1,1,1])

    d_conv_filter2=convolution(a1, d_a2, [1,1,1])
    #print(d_conv_filter2.shape)
    d_a1=deconvolution(d_a2, np.transpose(conv_filter2, (0,2,1)), [1,1,1])

    d_conv_filter1=convolution(IP, d_a1, [1,5,5])
    #print(d_conv_filter1.shape)

    return d_conv_filter1, d_conv_filter2, d_conv_filter3, d_deconv_filter1, d_deconv_filter2, d_deconv_filter3

DATA LOADING:

In [11]:
dataset_path="D:\PROJECT\CIFAR10\\train"

#Hypreparameters
epochs=15
learning_rate=0.0000000001
batch_size=1
image_size=[3,32,32]

In [12]:
def load_image_paths():
    """Loads all image file paths from the dataset directory."""
    supported_formats = ('.png', '.jpg', '.jpeg', '.bmp')
    image_paths = [os.path.join(dataset_path, f) for f in os.listdir(dataset_path) 
                    if f.endswith(supported_formats)]
    return image_paths
    
def load_image(image_path):
    """Loads an image, resizes it, and normalizes pixel values to the range [0, 1]."""
    image = cv2.imread(image_path)
    if image is None:
        raise ValueError(f"Could not load image: {image_path}")
    #Eimage = cv2.resize(image, image_size)
    image = image.astype(np.float64) / 255.0  # Normalize to [0, 1]
    return image

TRAINING THE MODEL:

print(np.mean(d_conv_filter1))
        print(np.mean(d_conv_filter2))
        print(np.mean(d_conv_filter3))
        print(np.mean(d_deconv_filter1))
        print(np.mean(d_deconv_filter2))
        print(np.mean(d_deconv_filter3))      

                if (batch_index+1)%10000==0:
            cv2.imshow("test", np.transpose(batch[0,:,:,:], (1,2,0)))
            cv2.waitKey(0)
            cv2.imshow("result", np.transpose(a6, (1,2,0)))
            cv2.waitKey(0)

In [13]:
def get_batch(image_paths):
    """Generates a batch of images for training."""
    batch_paths = np.random.choice(image_paths, batch_size, replace=False)
    images = np.array([load_image(path) for path in batch_paths])
    return images
    
image_paths = load_image_paths()
for epoch in range(epochs):
    total_loss = 0
    num_batches = len(image_paths) // batch_size
        
    for batch_index in range(num_batches):
        batch = get_batch(image_paths)
        batch=np.transpose(batch, (0,3,2,1))
        # Forward pass through the model
        t=batch[0,:,:,:]
        results = forward_pass(batch[0,:,:,:])
        a6, a5, a4, a3, a2, a1=results
            
        # Compute error (assume the error function is already implemented in the model)
        loss = np.mean(square_error(batch[0,:,:,:], a6))
            
        # Backward pass to compute gradients
        box=backward_pass(batch[0,:,:,:], results)
            
        # Update model parameters (assume the model has a method to update its parameters)
        d_conv_filter1, d_conv_filter2, d_conv_filter3, d_deconv_filter1, d_deconv_filter2, d_deconv_filter3=box
        conv_filter1=conv_filter1-learning_rate*d_conv_filter1
        conv_filter2=conv_filter2-learning_rate*d_conv_filter2
        conv_filter3=conv_filter3-learning_rate*d_conv_filter3
        deconv_filter1=deconv_filter1-learning_rate*d_deconv_filter1
        deconv_filter2=deconv_filter2-learning_rate*d_deconv_filter2
        deconv_filter3=deconv_filter3-learning_rate*d_deconv_filter3
        
        print(np.mean(d_conv_filter1))
        print(np.mean(d_deconv_filter1))
        total_loss += loss

        if loss <= 0.02:
            cv2.imshow("test", np.transpose(batch[0,:,:,:], (1,2,0)))
            cv2.waitKey(0)
            cv2.imshow("result", np.transpose(a6, (1,2,0)))
            cv2.waitKey(0)
            print(loss)
            
        if (batch_index + 1) % 10 == 0:
            print(f"Epoch [{epoch+1}/{epochs}], Batch [{batch_index+1}/{num_batches}], Loss: {loss:.4f}")
        
    avg_loss = total_loss / num_batches
    print(f"Epoch [{epoch+1}/{epochs}] completed. Average Loss: {avg_loss:.4f}")

-658.9657546958342
-2441.904169633924
-3007.567768227685
-6588.390506697462
-2455.402112336748
-5044.686474852814
2427.588228210838
-2690.9164352536736
111.00489324888504
817.8091418853487
-1289.813577904922
-400.22723897477744
1233.1759054670058
746.2587836388033
3676.9381110229037
-1967.4996847007553
1247.8191630858873
-3046.1348020200567
1422.6178459886905
-4688.774507551957
Epoch [1/15], Batch [10/50000], Loss: 1096.9276
-2029.9118752742804
130.2168316780259
124.26318531073086
-94.7265819668271
3699.8793472638426
499.7172613413571
-6830.522470670589
-681.5590722280799
-10593.001002281273
229.1771246030752
-535.7463942347314
283.0998652321175
4719.267811258805
4236.506547690541
-1204.6916119561877
545.876149305394
3325.5775755381096
8991.692030179986
-952.9086831934413
-34.1490137941984
Epoch [1/15], Batch [20/50000], Loss: 1439.6335
-724.7938114956179
2829.867658103456
478.0518733376434
-6327.469329228955
1288.8177604023897
429.18077138930266
2560.812356925356
-124.14986370469445
-

KeyboardInterrupt: 